### ISSUE TITLE
No Notifications when updates to theme are made 

### ISSUE THREAD

**Issue by millry** [afragen/github-updater#449]
I have successfully installed the plugin and the theme but when I make a commit to my Git repo with the updated version and tag, there is no notification on the wordpress admin page. 

When opening my theme window, I can re-install the same branch and the version becomes up to date. But there are no notifications when a new version is available. 

Any advice?

**Comment by afragen** [comment]
Transients are cached for 12 hours. You can Refresh Transients from the Settings page.

**Comment by millry** [comment]
Refreshed the transients but did not get the update alert on my WP admin page. Could it be any other issues? Should I be seeing the update alert immediately after I make my commit to the Git branch?

**Comment by millry** [comment]
In my style.css header I have 
```Theme:
Author:
Description:
Github Theme URI: https://github.com/....
Version: 0.0.9
GitHub Branch: plugin-test```

**Comment by afragen** [comment]
You should not see an update immediately after a commit. Seeing the complete header would be helpful as I can't tell much from what you've provided. Sorry.

Is this the first time you've used the plugin? Just asking.

**Comment by afragen** [comment]
As it's a private repo do you have an appropriate access token designated in the Settings?

**Comment by millry** [comment]
Yes, this is my first time using it. Trying it out with a custom theme. It is a private repo and I added the the access token and have it configured. 

The theme uploads successfully, so I think there is something I'm not doing correctly, preventing the updater plugin from syncing with the git repo.

Thanks for the help, I really appreciate it.

**Comment by millry** [comment]
One of the things I'm trying to understand is the directory matching the directory being identical to the repo name. How do I figure out (or change) what my directory name?

**Comment by afragen** [comment]
You could install the theme using GitHub Updater and the renaming will just happen. It's possible with themes that an incorrectly named directory can cause issues.

**Comment by afragen** [comment]
Alternatively, can you email me an access token so that I may try and install and update? Or just give my user read access.

**Comment by afragen** [comment]
It's possible that this update to the develop branch may fix your problem. https://github.com/afragen/github-updater/commit/78ecdd91bc0173a5e1361af505b55188507804b4

Using the _Refresh Transients_ button in the Settings page now resets the _update\_plugins_ and _update\_themes_ transients.

**Comment by millry** [comment]
Hey Andy - 

We uploaded the zip to a public repo here: https://github.com/AssociationForComputingMachinery/ACM-Wordpress-Theme

Can you help debug? 

Steps we took:
1. Downloaded your plugin, renamed plugin to github-updater and re-zipped. 
2. Successfully installed the plugin to WP
3. Successfully installed the theme 'version 1.0.0' through the plugin using the git URI. 
4. Made a test update to the theme and updated the version to '1.0.1' and pushed to git repo.
5. Waiting to see update notification in WP. Nothing yet. 

Thanks!

**Comment by millry** [comment]
Also, just curious...

When or where is the updater checking for updated versions on a git repo?

**Comment by afragen** [comment]
Transients are set for 12 hr expiration, if you click **Refresh Transients** from Settings page it should recheck right away.

I was having an issue with the _update\_themes_ transient not refreshing so even if GHU had an update it wouldn't show, but this should be fixed in the develop branch.

**Comment by millry** [comment]
I just uploaded the plugin from develop and installed it to WP, then installed my theme and made a version change and commit to Git. 

I clicked the 'Refresh Transients' button in Settings and still don't see an update notification.

I'm wondering if there's something wrong with the way I implemented the heading in style.css

**Comment by millry** [comment]
Ok the update just came through...I had to click update transients a couple times but downloaded successfully. 

Going to update to a new version and check again tomorrow. Will let you know tomorrow.

**Comment by millry** [comment]
I am seeing the update on my WP instance, thanks for the help! Closing the issue now.
