### ISSUE TITLE
GitLab: No different Version is shown

### ISSUE THREAD

**Issue by marbetschar** [afragen/github-updater#465]
When I've installed a theme using your GitHub Updater plugin from GitLab, I'm not able to switch to any different version - since no earlier tags are shown (see the following screenshot).

This issue might be related to #464 

<img width="1029" alt="bildschirmfoto 2016-10-13 um 00 50 57" src="https://cloud.githubusercontent.com/assets/392542/19330528/47021882-90df-11e6-891d-7f9c88ba9914.png">

**Comment by afragen** [comment]
Can you give `afragen` `read` access?

**Comment by afragen** [comment]
Are you sure the private token is entered correctly?

**Comment by marbetschar** [comment]
@afragen just provided you access to the repo. Yes, I've double checked the token - everything seems fine.

**Comment by afragen** [comment]
So I was able to install. I did change the template as I don't have the parent theme installed.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/19333571/bf7658ca-90ab-11e6-96b2-de27247466e7.png)

I will state that I'm on the develop branch but I don't think there's a difference in that particular code.

**Comment by marbetschar** [comment]
I've again created a new token, changed the settings, refreshed the Transients and played with the `Activate Plugin Branch Switch` Checkbox in the GitHub Updater settings.

Nothing worked :(

FWIW: I don't have any GitHub settings configured. And here's what I configured for the access token when I've revoked the old and created the new one:

<img width="1239" alt="bildschirmfoto 2016-10-13 um 04 07 14" src="https://cloud.githubusercontent.com/assets/392542/19334265/04635dda-90fb-11e6-9549-791e0b019717.png">

**Comment by afragen** [comment]
Just check to make sure the token is still set. In GitLab it's called a private token, under the Account tab. I didn't know they had personal access tokens. I don't think GHU is set for them -- yet.

**Comment by afragen** [comment]
A quick look at the GitLab API seems like the private token and personal access token would be interchangeable for our purposes.

**Comment by marbetschar** [comment]
Ok. I've now used the private token and manually installed the GHU develop branch - still no success. For some reason I've also don't seem to be able to switch branches; at least I've checked the setting and can't see any possibility to switch branches in the plugin listing:

<img width="1108" alt="bildschirmfoto 2016-10-13 um 04 37 01" src="https://cloud.githubusercontent.com/assets/392542/19334796/fcbff6fc-90fe-11e6-88c0-559e5a19175b.png">

**Comment by afragen** [comment]
Can you show the GitHub Updater Settings?

**Comment by marbetschar** [comment]
Here you go:

<img width="886" alt="bildschirmfoto 2016-10-13 um 10 01 04" src="https://cloud.githubusercontent.com/assets/392542/19341076/4018b52e-912c-11e6-89f6-2e0b0e4615a5.png">
<img width="810" alt="bildschirmfoto 2016-10-13 um 10 01 16" src="https://cloud.githubusercontent.com/assets/392542/19341074/4015f686-912c-11e6-8ed8-ed4e1f8f273f.png">
<img width="693" alt="bildschirmfoto 2016-10-13 um 10 01 28" src="https://cloud.githubusercontent.com/assets/392542/19341075/4015ddc2-912c-11e6-96be-f7b391ef4727.png">
<img width="947" alt="bildschirmfoto 2016-10-13 um 10 01 53" src="https://cloud.githubusercontent.com/assets/392542/19341073/40143ae4-912c-11e6-84ee-820ce909dc62.png">

**Comment by afragen** [comment]
Everything looks correct. Can you try Refresh Transients again.

**Comment by marbetschar** [comment]
Done. Still the same issue.

May I hand over the wp admin credentials to you somehow so you're able to debug the issue directly?

**Comment by afragen** [comment]
I think that's the next step. You should install https://wordpress.org/plugins/support-me/ to set up expiring credentials. I have a sort of busy day ahead but I'll see what I can get to. I will likely install Query Monitor plugin too. I'll remove after if it's not already installed.

**Comment by marbetschar** [comment]
@afragen whatever it takes! ;) Password url is on it's way to andy@thefragens.com

And thank you very much for this AWESOME support, I really appreciate it!!!

**Comment by afragen** [comment]
I was able to log in and installed Query Monitor. You must have a plugin conflict as Query Monitor's menubar doesn't even show.

**Comment by afragen** [comment]
If you have a staging site I would suggest turning off plugins until we find the one with the issue.

**Comment by marbetschar** [comment]
I've just created a 1:1 copy for it here https://pizza.mandelkind.work

Feel free to modify anything you like! Support user is the same as on the other site.

**Comment by afragen** [comment]
Great. Just getting started in OR, I should have more time later today.

**Comment by afragen** [comment]
So on the copy. I've turned off all the plugins except GitHub Updater and Query Monitor and Query Monitor doesn't show it's adminbar. I'm on one of the default themes too.

What's the setup of this server? Is there caching Varnish, Redis, or something else? At a minimum I should be able to see Query Monitor's stuff.

On the plus side, after a  Refresh Transients, GitHub Updater did recognize it had an update for itself.

**Comment by afragen** [comment]
I don't know if this has anything to do with the privileges that Support Me provides. We might need to create a full admin user, at least on the staging site.

**Comment by afragen** [comment]
I'm getting somewhere. Once I updated GHU and it's directory became renamed correctly things started working. Query Monitor still isn't working though. I'm testing other plugins now.

**Comment by afragen** [comment]
Marco, I have no idea what's going on at your server but something isn't working correctly. I've changed branches, changed tagged versions, and I find the directory of the new update/switch has changed. I don't mean changed from `github-updater` to `afragen-github-updater-73u4iqgrp9evu`. I mean from `github-updater` to `enfold-mandelkind`. This is bizarre.

I'm not sure what's going on but GHU does recognize updates, etc.

**Comment by afragen** [comment]
What I did find was that after updating GitHub Updater so that the directory name is `github-updater` and not `github-updater-develop`, everything else seems to be working. I updated the plugin on the main site. You'll have to reinstall the GitLab access token in the settings.

**Comment by afragen** [comment]
To see what I mean about the directory renaming, look at the name of the Mandelkind theme directory on the staging site.

**Comment by marbetschar** [comment]
@afragen thanks for debugging this issue!

I have no clue why things are going that weird on the server - it's a regular https://easyengine.io WordPress setup. Nothing special configured.

Any idea how we may fix that? What's even worse is, until now I didn't recognize this issue at all - that said, the regular WordPress theme and plugin updates work all as expected, no issues there.

So from that perspective my obvious choice to seek for errors is/was GHU. Do you have any idea, how we can track the issue further down to get to a real solution? Unfortunately I'm a bit loss right now :(

**Comment by marbetschar** [comment]
Maybe some sort of environmental/cgi variables which do not contain the values they should in an Easy Engine setup?

**Comment by afragen** [comment]
I honestluy out of ideas other that duplicating the site on localhost and testing there to rule out anything on the server. At this point, GHU seems to pick updates, but from what I've seen it's unpredictable and not in a good way. 

If everything works in localhost then I would consider EasyEngine a possible issue, sorry.

**Comment by afragen** [comment]
I think I did figure out the renaming issue. That was all my fault. It's fixed in latest `develop`.

Can you update to latest `develop` branch and try again? I'm hoping this is my fault and not something screwy in your stack.

**Comment by marbetschar** [comment]
I've just installed the `develop` branch in https://pizza.mandelkind.work, and also reset the theme used to `v0.0.6`.

But after deleting the transients, forcing an update check etc. WordPress still does not show the new `v0.1.1` of the theme. Also no additional branch is showed which I may switch to manually.

**Comment by afragen** [comment]
I think it's fixed. Here's what I did. 

I seems that if the GitHub Updater plugin's directory is not initially named `github-updater` then then plugin fails to initialize. I'll have to work on that. I managed to get an update of GHU so that the directory now is correct. I had to re-enter a GitLab.com access token. I created a temporary one so you will need to replace this. I refreshed transients and now it all seems to be working.

I need to work on the issue I noted above, but your site should now be working.

**Comment by marbetschar** [comment]
I'm still out of luck regarding this issue - no clue why. I've installed the GHU develop branch & made sure the plugins directory is called `github-updater`. After all of this I've clicked on `Refresh Cache` - but still no new version is displayed over at https://mandelkind.pizza.

On the other hand I can see the new version at https://pizza.mandelkind.work. Something seems still to be wrong? I've installed the following version at https://mandelkind.pizza:

<img width="1089" alt="bildschirmfoto 2016-10-26 um 16 41 37" src="https://cloud.githubusercontent.com/assets/392542/19730711/61858f7e-9b9b-11e6-888e-94a0a4a9f6e7.png">

**Comment by afragen** [comment]
Reset your GitLab Access Token.

**Comment by marbetschar** [comment]
Still no luck: I've even revoked and regenerated the Private Access Token on GitLab.com - and of course pasted it into GHU again. But the update still does not show up in WordPress.

What's weird though is, the admin bar shows 2 updates. But visible is only one if I go to Dashboard / Updates: <img width="49" alt="bildschirmfoto 2016-10-26 um 20 14 52" src="https://cloud.githubusercontent.com/assets/392542/19738795/03f0c9c8-9bb9-11e6-8948-4a2019471808.png">

<img width="1105" alt="bildschirmfoto 2016-10-26 um 20 14 57" src="https://cloud.githubusercontent.com/assets/392542/19738798/0a206376-9bb9-11e6-97da-a99072df77ab.png">

**Comment by afragen** [comment]
Strange as I added my access token, refreshed transients and everything worked. Go to either site now.

I added a GitLab access token to both sites, refreshed and it seems to work. When the new access token is created, select the code and copy it, save it somewhere, don't use the clipboard copy icon.

**Comment by marbetschar** [comment]
I'm just about giving up since GHU does not want to work as expected:

1. Refreshing the Cache does not seem to have any effect
2. After waiting a few minutes I've seen an update showing up; but it shows the `v0.1.4` tag - ignoring the fact that the newest tag is `v0.1.5`.
3. GHU still does not give me the ability to switch branches, as the pulldown menu is just empty:

<img width="1089" alt="bildschirmfoto 2016-10-26 um 20 46 08" src="https://cloud.githubusercontent.com/assets/392542/19740054/8fb94fee-9bbd-11e6-8be0-efb72f44a89e.png">

The site affected is https://mandelkind.pizza - I can provide you a login if you like to, but it looks like GHU got major issues when used together with GitLab.com :(

**Comment by afragen** [comment]
Your recent 0.1.5 tag does not have the same version in `master` branch. As such no update will show up. Your current `master` has version 0.1.4

![screenshot_03](https://cloud.githubusercontent.com/assets/1296790/19743011/53d415f4-9b7c-11e6-895d-e319f6e1d36d.png)

**Comment by afragen** [comment]
> Refreshing the Cache does not seem to have any effect
> After waiting a few minutes I've seen an update showing up; but it shows the 0.1.4 tag - ignoring the fact that the newest tag is 0.1.5.

The update process gets its version number from the current branches header. Your current branch header says version 0.1.4, so no update will show.

> GHU still does not give me the ability to switch branches, as the pulldown menu is just empty:

When this is empty, it means that your access token is not valid. Please create a new one and use it. I have entered a temporary one for you that works and will be valid through the end of November.

**Comment by marbetschar** [comment]
@afragen to get this straight: Which Access Token do I have to use in order for GitLab.com to work? I've now used the `Private Token` which is located under `Profile Settings / Account / Private Token` - since you said in the beginning you were not aware of the `Personal Token`.

**Comment by afragen** [comment]
It was my impression that either a private token or an access token would work. Your experience seems to indicate that only an access token will work. It's probably safer to use an access token in any event.

**Comment by marbetschar** [comment]
I've just generated a new `Personal Access Token` and added it to GHU. Same issues as with the `Private Token`. Can you please tell me what's wrong with this token: `RshqTcnCzQftUgN859hN`

I've created it using the user `MANDELKIND`, which is a `Master` - member in the project:

<img width="1233" alt="bildschirmfoto 2016-10-26 um 22 24 43" src="https://cloud.githubusercontent.com/assets/392542/19743813/229bca0a-9bcb-11e6-9f98-6e3e78216422.png">

**Comment by afragen** [comment]
I don't know but it doesn't work for me.

**Comment by afragen** [comment]
Were all these tokens created under user MANDELKIND?

**Comment by marbetschar** [comment]
Yes, since this is the main account. Next I'm trying to create a token under my personal account - just for testing purposes. One moment...

**Comment by marbetschar** [comment]
I'm just running out of ideas: I've degraded my personal account to `Developer` and created a new token. Same error. Then I`ve even degraded my personal account to `Reporter` and again created a new token; same result.

Do you have any clue what's going wrong here?

**Comment by marbetschar** [comment]
Just tested the created Token for the user `MANDELKIND`. And the following call retrieves successfully some of the projects for this user:

`curl --header "PRIVATE-TOKEN: my-generated-token" "https://gitlab.com/api/v3/projects"`

So obviously the token is valid.

BUT: This request does not receive the theme project information. So I assume we got some sort of paging issue here, since the GitLab API seems not to return all records.

**Comment by afragen** [comment]
I've no idea. You should raise a ticket with GitLab. In the interim, I'll create a token good through the end of the year. Hopefully that should be enough time to figure it out. To test whether the token is any good just try to install a GitLab plugin/theme and use the token in the Install tab.

You should try the following to test.
`curl "https://gitlab.com/api/v3/projects?private_token=my_generated_token"`

That's more consistent with how we use it.

**Comment by afragen** [comment]
I sent you an email with a token that works for me.

**Comment by marbetschar** [comment]
First of all; Thank you very much for all of your support and your patience with this issue! I REALLY appreciate it!!!

Aaaaaaand second:  I've just figured it out: It's definitely a paging issue. GitLab returns the paging information with the following headers: `X-Total,X-Total-Pages,X-Per-Page,X-Page,X-Next-Page,X-Prev-Page`.

When I run

```
curl -v "https://gitlab.com/api/v3/projects?private_token=my_generated_token"
```

The following headers are returned:

```
< Server: nginx
< Date: Wed, 26 Oct 2016 21:06:45 GMT
< Content-Type: application/json
< Content-Length: 34370
< Cache-Control: max-age=0, private, must-revalidate
...
< Vary: Origin
< X-Next-Page:
< X-Page: 2
< X-Per-Page: 20
< X-Prev-Page: 1
< X-Request-Id: 3f28a01a-cd68-4180-89ed-aaf9a018e54c
< X-Runtime: 1.075393
< X-Total: 39
< X-Total-Pages: 2
...
```

And guess what, when I then execute the following query GitLab.com returns the theme project information:

```
curl -v "https://gitlab.com/api/v3/projects?private_token=my_generated_token&page=2"
```


For more information about the GitLab.com paging headers see https://docs.gitlab.com/ee/api/

**Comment by afragen** [comment]
Hmm, trying to set the page for the query will be futile. It there a way to return all?

BTW, I sent an invite to the Slack team if you want to continue there. It seems the issue is somewhere in GitLab and not the plugin.

**Comment by afragen** [comment]
Is there a way to get everything in the one call without paging?

**Comment by marbetschar** [comment]
Unfortunately I can't see any solution to get all projects at once and the maximum for `per_page` is `100` according the docs.

Also there is an endpoint called `/projects/all`, but it's for admins only. That said, it's not suitable for GitLab.com. (I've tested it with the user role `Master` and a `403 Forbidden` was returned).

Details here: https://docs.gitlab.com/ce/api/projects.html#projects`

**Comment by afragen** [comment]
Added `per_page=100` to the API call.
