### ISSUE TITLE
Bitbucket Private Repo with Release Assets: Package download says Bad Request

### ISSUE THREAD

**Issue by mcguffin** [afragen/github-updater#714]
Hello,

I was struggeling to set up a theme deployment workflow with a private repository hosted on bitbucket using release assets. 

When WP tries to download the package it failed, saying "Bad Request".

I dug into it, looking closely at each cURL request WP is performing, and presumably was able to spot the cause:
 1. The initial Download URL is something like `https://bitbucket.org/<owner>/<repo>/downloads/<repo>-<tag>.zip`. HTTP Basic auth credentials are sent along to Bitbucket.
 2. Bitbucket responds with a 302 redirect to a Amazon S3 Bucket or something alike. 
 3. WordPress opens a second curl request, using the redirect URL. The HTTP Basic Auth header is still present in the follow up request. Amazon doesn't like it.

That' what the response looks like:
```
string(806) "HTTP/1.1 400 Bad Request
x-amz-request-id: <SOME_ID>
x-amz-id-2: <SOME_LONGISH_ID_LOOKING_LIKE_BASE64>
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Wed, 12 Sep 2018 15:43:01 GMT
Connection: close
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Basic [HTTP_BASIC_AUTH_HEADER_VALUE]</ArgumentValue><RequestId>[SOME_ID]</RequestId><HostId>[SOME_LONGISH_ID_LOOKING_LIKE_BASE64]</HostId></Error>
```

I finally managed to solve my task by simply deactivating release assets, but I'd like to share my findings here, in case someone runs into the same issue.

Regards,
jörn

**Comment by afragen** [comment]
Thanks for the report. I guess Bitbucket now stores their release assets on Amazon. I fixed this issue for GitHub. The issue is that the amazon link expires after 5 minutes. 

If you could give `afragen` `read` access to the repository I can test and fix this.

**Comment by afragen** [comment]
BTW, you really only need to use release assets if there are build steps in you plugin/theme.

**Comment by mcguffin** [comment]
Thanks for the offer and the hint. 
I have already switched the Release Asset header to `false` in my repo (it's a job I'm currently working on, and I had to move forward), so it wouldn't be helpful in reproducing the issue anyway. 
I sat up another blank theme instead (just a blank `_s`) and gave you read access. The error still occurs when I try to run the update.
Thanks again for caring!

**Comment by afragen** [comment]
Thanks. I don’t think I had anyone creating a release asset with Bitbucket previously. It almost seems like it will be very similar to GitHub in that release assets are stored on AWS and the direct link has a 5 minute expiration. 

Thanks for the access. I’ll let you know when I’ve got something for you to test.

**Comment by afragen** [comment]
I did a quick test and I’m getting the same sort of authentication error. The Basic Auth header is sent but not sure what is required. 

I’ll keep looking.

**Comment by mcguffin** [comment]
According to my own testings, I guess it's just HTTP Auth Header (the bitbucket login) in the second (the amazon) request, that needs to be removed. The response from amazon seems quite distinct to me – `... Only one auth mechanism allowed; ...`.

**Comment by afragen** [comment]
Thanks. I think I know what I can do for that but I’m heading out of town until next week so I won’t be able to test. 

I’ll try to have something next week. Stay tuned.

**Comment by mcguffin** [comment]
Hi Andy,
I think I was able fix it. 
There are a couple of undocumented WordPress Actions in the `Requests` class (`wp-includes/class-requests.php`). One of them is `requests-requests.before_redirect`, which gets fired before WP follows a redirect.
All I had to do then was to check if a request to an amazon AWS has a) a HTTP Basic Auth in the request header and b) an AWS-specific Auth in the query string and if so, get rid of the Basic Auth.

Please have a look at this commit: https://github.com/mcguffin/github-updater/commit/36179ee555d9b2bfca537d1650a103147a7754dd
In theory the fix should work for each and every download from amazon AWS, not just on the bitbucket subdomain (`bbuseruploads.s3.amazonaws.com`). 
I think you might want to include it in the `API` class, and not just in the `Bitbucket_API`, like me. (That's why I didn't send a PR.)

Hope I could help...

**Comment by afragen** [comment]
I will take a look today or as soon as I have time. Thanks.

**Comment by afragen** [comment]
@mcguffin I have added your code and the $location returned to the function is `https://bitbucket.org/account/signin/?next=/joernlund/ghu-tester/downloads/ghu-tester-1.0.4.zip`

Trying to look deeper.

**Comment by afragen** [comment]
I've created branch `bb-release-asset` which should have your changes. Feel free to make PRs against it.

https://github.com/afragen/github-updater/tree/bb-release-asset

**Comment by afragen** [comment]
@mcguffin take a look at this function.

 https://github.com/afragen/github-updater/blob/53dcf99a9813132d17a627892f81bc25a79c12df/src/GitHub_Updater/Traits/Basic_Auth_Loader.php#L229-L236

It runs with `load_authentication_hooks()` and has been present for a while.

**Comment by afragen** [comment]
Any news @mcguffin? I haven't been able to make this work.

Your other hint about `requests-requests.before_redirect` is great, thanks!

**Comment by afragen** [comment]
@mcguffin I think this is fixed in the `develop` branch with the above commit.

It seems there's a new API endpoint that it took me a while to find.
